### ISSUE TITLE
mat_number identity protection

### ISSUE THREAD

**Issue by physikerwelt** [KITPraktomatTeam/Praktomat#277]
For identity protection, the actual mat_number cannot be retrieved from shibboleth at my university. I appreciate that in principal. However, paktomat requires a unique mat_number of type integer. Our mat_number is of type string. After changing the data type, I could not run the migration script 
`./src/manage-local.py makemigrations` which failed with the error below.
Thus, I had to 
```SQL
ALTER TABLE public.accounts_user
  ALTER COLUMN mat_number TYPE VARCHAR(100) USING mat_number :: VARCHAR(100);
```
.
However, since we are considering to use praktomat for a second course in the same semester this becomes inconvenient.

Error message:
```python
Traceback (most recent call last):
  File "./src/manage-local.py", line 8, in <module>
    from django.core.cache import CacheKeyWarning
  File "/srv/praktomat/env/local/lib/python2.7/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/srv/praktomat/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/srv/praktomat/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/srv/praktomat/env/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/praktomat/src/settings/local.py", line 56, in <module>
    raise NotImplementedError("Autoconfig for PRAKTOMAT_ID %s not possible", PRAKTOMAT_ID)
NotImplementedError: ('Autoconfig for PRAKTOMAT_ID %s not possible', 'srv')
```

**Comment by physikerwelt** [comment]
oups. I used the wrong script `./src/manage-devel.py makemigration` works fine.
