### ISSUE TITLE
Unable to build docker image

### ISSUE THREAD

**Issue by lohner** [KITPraktomatTeam/Praktomat#286]
I tried building the docker image from the provided `docker-image/Dockerfile` via `docker build -t praktomat docker-image`, but got the following error:

```
Step 25/42 : RUN pip3 install arch
 ---> Running in 209d4d76fe89
Collecting arch
  Downloading arch-4.3.1.tar.gz (363kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jsnv0xpk/arch/setup.py", line 13, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jsnv0xpk/arch/
The command '/bin/sh -c pip3 install arch' returned a non-zero code: 1
```

Perhaps this is due to misconfigured dependencies in `arch`. However, manually installing packages `pandas` and `Cython` prior to `arch` solved the issue for me.

**Comment by ratefuchs** [comment]
Fixed in 5d060f95.
