### ISSUE TITLE
ERROR and FAIL in test_r_checker / test_r_checker_2:     (r-base-core was missing)

### ISSUE THREAD

**Issue by ifrh** [KITPraktomatTeam/Praktomat#303]
ERROR: test_r_checker (checker.tests.TestChecker)
=====================================
Console output
----------------------------------------------------------------------
```
Traceback (most recent call last):
  File "/home/praktomat/inst4git/p4merge2019/Praktomat/src/checker/tests.py", line 322, in test_r_checker
    self.solution.check_solution()
  File "/home/praktomat/inst4git/p4merge2019/Praktomat/src/solutions/models.py", line 89, in check_solution
    check_solution(self, run_secret, debug_keep_tmp)
  File "/home/praktomat/inst4git/p4merge2019/Praktomat/src/checker/basemodels.py", line 292, in check_solution
    run_checks(solution, env, run_all)
  File "/home/praktomat/inst4git/p4merge2019/Praktomat/src/checker/basemodels.py", line 353, in run_checks
    result = checker.run(env)
  File "/home/praktomat/inst4git/p4merge2019/Praktomat/src/checker/checker/RChecker.py", line 84, in run
    maxmem=settings.TEST_MAXMEM,
  File "/home/praktomat/inst4git/p4merge2019/Praktomat/src/utilities/safeexec.py", line 75, in execute_arglist
    preexec_fn=prepare_subprocess)
  File "/home/praktomat/anaconda3/envs/apy35d22/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/home/praktomat/anaconda3/envs/apy35d22/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'Rscript'
```

FAIL: test_r_checker_2 (checker.tests.TestChecker)
===========================================================
Console output
---------------------------------------------------------------------
```
Traceback (most recent call last):
  File "/home/praktomat/inst4git/p4merge2019/Praktomat/src/checker/tests.py", line 354, in test_r_checker_2
    self.assertIn('2', checkerresult.log, "Test did not calculate 1 + 2 (%s)" % checkerresult.log)
AssertionError: '2' not found in '<p>Could not find expected R script example.R.</p><p>R scripts found: example_1tJvcZv.R</p>' : Test did not calculate 1 + 2 (<p>Could not find expected R script example.R.</p><p>R scripts found: example_1tJvcZv.R</p>)

```
----------------------------------------------------------------------

====================================

Perhaps one could mention in `README.md`  that for not failing in
`./src/manage-test.py test accounts attestation checker configuration solutions tasks`
Rscript has to be installed:
`sudo apt-get install r-base-core`

**Comment by ratefuchs** [comment]
Fixed in 7983241.

**Comment by ifrh** [comment]
Some thing is missing on my other installation. Has any one an Idea?

```
$ sudo apt install r-base
Reading package lists... Done
Building dependency tree
Reading state information... Done
r-base is already the newest version (3.4.4-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

```
$ sudo apt install r-base-core
[sudo] password for ich:
Reading package lists... Done
Building dependency tree
Reading state information... Done
r-base-core is already the newest version (3.4.4-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

lets test, if R and Rscript are found...

```
$ Rscript --version
I am an debugging Wrapper around /usr/bin/Rscript
calling: /usr/bin/Rscript --version
R scripting front-end version 3.4.4 (2018-03-15)
Return code was: 0
```
```
$ R --version
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

```

R and Rscript are found, but Praktomats `manage-test.py` fails while running tests for 

```
$ ./src/manage-test.py test accounts attestation checker configuration solutions tasks

Creating test database for alias 'default'...
System check identified no issues (0 silenced).
............................FF...Fs................./home/ich/inst/integrate/py3env/lib/python3.6/site-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
.
======================================================================
FAIL: test_r_checker (checker.tests.TestChecker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ich/inst/integrate/Praktomat/src/checker/tests.py", line 326, in test_r_checker
    self.assertTrue(checkerresult.artefacts.exists())
AssertionError: False is not true

======================================================================
FAIL: test_r_checker_2 (checker.tests.TestChecker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ich/inst/integrate/Praktomat/src/checker/tests.py", line 348, in test_r_checker_2
    self.assertIn('2', checkerresult.log, "Test did not calculate 1 + 2 (%s)" % checkerresult.log)
AssertionError: '2' not found in '<p>Could not find expected R script example.R.</p><p>R scripts found: example_Dcrswph.R</p>' : Test did not calculate 1 + 2 (<p>Could not find expected R script example.R.</p><p>R scripts found: example_Dcrswph.R</p>)

======================================================================
FAIL: test_script_filesizelimit (checker.tests.TestChecker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ich/inst/integrate/Praktomat/src/checker/tests.py", line 212, in test_script_filesizelimit
    self.assertNotIn('End', checkerresult.log, "Test did finish (no timeout?) (%s)" % checkerresult.log)
AssertionError: 'End' unexpectedly found in '<pre>Begin\nEnd\n</pre>' : Test did finish (no timeout?) (<pre>Begin
End
</pre>)

----------------------------------------------------------------------
Ran 53 tests in 99.666s

FAILED (failures=3, skipped=1)
Destroying test database for alias 'default'...
```

**Comment by ifrh** [comment]
Adding `self.assertNotIn('Fatal error',checkerresult.log, "(%s)" % checkerresult.log)` to the checkerresult-loop in method `test_r_checker` then I got an meaningfull message ... but very strange:
```

======================================================================
FAIL: test_r_checker (checker.tests.TestChecker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ich/inst/integrate/Praktomat/src/checker/tests.py", line 321, in test_r_checker
    self.assertNotIn('Fatal error',checkerresult.log, "(%s)" % checkerresult.log)
AssertionError: 'Fatal error' unexpectedly found in '<pre>Fatal error: the limit on the number of open files is too low\n\n\n---- Rscript finished with exitcode 2 ----\n</pre>' : (<pre>Fatal error: the limit on the number of open files is too low


---- Rscript finished with exitcode 2 ----
</pre>)

======================================================================
```

But running `Rscript `directly, I got:
```
(py35d22) ich:~/inst/integrate/Praktomat/examples$ Rscript example.R
[1] 3
[1] 1 1 2
```
and `Rplots.pdf` was generated.
